import { useRef, useState } from 'react';
import PosterCanvas from './PosterCanvas.jsx';
import BookRow from './BookRow.jsx';

const TODAY = new Date().toLocaleDateString('en-US', {
  month: 'long',
  day: 'numeric',
  year: 'numeric',
});

// The generated read-down, laid out like a real PRH Read Down article: a hero
// (here, the generative cover), an editorial header, then a column of book cards.
export default function ListView({ list, onReset }) {
  const posterRef = useRef(null);
  const [copied, setCopied] = useState(false);

  const meta = { bookCount: list.items.length };
  const byline = list.source === 'ai' ? 'The ReadDown, curated with AI' : 'The ReadDown';

  const share = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
    }
  };

  const download = () => {
    const name =
      list.listTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') ||
      'read-down-poster';
    posterRef.current?.download(name);
  };

  return (
    <section className="list-view">
      <div className="rd-hero">
        <div className="poster-wrap">
          <PosterCanvas ref={posterRef} prompt={list.prompt} meta={meta} size={{ w: 2000, h: 380 }} />
        </div>
      </div>

      <header className="rd-header">
        <p className="eyebrow"><span className="eyebrow-mark">The ReadDown</span></p>
        <h1 className="list-title">{list.listTitle}</h1>
        <p className="rd-byline">
          by <strong>{byline}</strong> <span className="rd-sep">|</span> Published on {TODAY}
        </p>
        {list.intro && <p className="rd-intro">{list.intro}</p>}
      </header>

      <div className="list-actions">
        <button className="btn-primary" type="button" onClick={share}>
          {copied ? 'Link copied ✓' : 'Copy shareable link'}
        </button>
        <button className="btn-ghost" type="button" onClick={download}>
          Download header image
        </button>
        <button className="btn-ghost" type="button" onClick={onReset}>
          Start over
        </button>
      </div>

      <ol className="rd-list">
        {list.items.map((book) => (
          <BookRow key={book.isbn} book={book} />
        ))}
      </ol>

      <p className="disclaimer">
        Proof of concept. Titles come from a seeded sample of the Penguin Random House
        catalog; covers and buy links resolve live by ISBN. The cover art is generated by a
        rule-based p5.js system &mdash; no AI image generation.
      </p>
    </section>
  );
}
